export const BOOKINGS_CONFIG = {
	RECOVERY_TOKEN_LIFETIME_MS: 15 * 60 * 1000,
	REQUEST_RESPONSE_WINDOW_MS: 24 * 60 * 60 * 1000,
	REQUEST_EXPIRATION_INTERVAL_MINUTES: 5,
	REQUEST_EXPIRATION_BATCH_SIZE: 25,
	RECOVERY_CLAIM_STORAGE_KEY: 'booking-recovery-claim',
	RECOVERY_TOKEN_CLEANUP_INTERVAL_MINUTES: 1,
	RECOVERY_TOKEN_CLEANUP_BATCH_SIZE: 100,
	RECOVERY_REQUEST_MIN_DURATION_MS: 500,
	RECOVERY_RESEND_COOLDOWN_MS: 60 * 1000,
	RECOVERY_REQUESTS_PER_HOUR: 5
};
